### ISSUE TITLE
Issue with new customers

### ISSUE THREAD

**Issue by ddymko** [MichaelThessel/magento-ee-ce-encryption#1]
This module works for existing magento customers who were created on EE. However now since we have downgraded all new customers that are created are not able to log in at all. Not sure what to do with this. 

Please let me know if there is something I am not doing properly!

**Comment by MichaelThessel** [comment]
Hi,

It works fine here with  1.9.2.1 for new customers as well as existing customers. The module should work out of the box without any additional configuration.

Can you do some more debugging?

Have a look at:
app/code/community/MichaelThessel/EnterpriseEncryption/Model/Encryption.php
line 51 validateHashByVersion()

**Comment by ddymko** [comment]
I actually reinstalled the module after trying to debug the issue and it works now! I guess something was not working properly the 1st time I installed the module. Thanks for your help!
