### ISSUE TITLE
can't get it working

### ISSUE THREAD

**Issue by quape** [MichaelThessel/magento-ee-ce-encryption#2]
Hi Michael,
nice module, it's exactly what I need but I cannot get it to work. I migrated Magento EE to CE and now all user logins don't work anymore. Can I check somehow if the module is activated on logging in? Or how can I debug this now...?

**Comment by MichaelThessel** [comment]
Have a look at: app/code/community/MichaelThessel/EnterpriseEncryption/Model/Encryption.php and debug validateHashByVersion() that should give you some clues why its not working. I assume you did all the usual, like check system and exception logs, cleared cache ...
